### ISSUE TITLE
Bower components per vendor module

### ISSUE THREAD

**Issue by nsarno** [luisfarzati/angulartics#225] opened 2014-10-15 09:35 UTC
It would be nice having the choice to install only one vendor module with Bower instead of all of them.

For example: `bower install angulartics-ga --save`

I'm not too sure how this would be possible without having to create one repo per vendor as bower doesn't seem to give the possibility to have multiple components per one repo (cf. [this discussion](https://github.com/bower/bower/issues/24)).

Thanks in advance for the feedback.

**Comment by jgentes** [comment] 2015-02-04 18:36
The 'overrides' workaround has stopped working for me, not sure why.

Would be great to see this in the next release :)

**Comment by timelf123** [comment] 2015-02-04 18:39
I'm working on 1.0.0 now :) It will be in a new repo/organization.

The core will be in it's own repo, and each provider also get's its own repo. This way you can install only the providers you need/use. It also makes integrating features easier.

Stay tuned! I know I promised this a few months ago and I apologize for the delay. That being said, I hope to get at least the new core out in a week or so

**Comment by jgentes** [comment] 2015-02-04 20:18
Great, thanks for all of the effort you put into this.

**Comment by aborchew** [comment] 2015-05-13 16:39
@timelf123 thanks for all the effort!
@rosslavery thanks for the workaround!

**Comment by luisfarzati** [comment] 2015-07-18 01:59
This is now being done gradually for each plugin. Please see #377 and https://github.com/angulartics/angulartics-google-analytics.

We'll be moving the rest of the plugins during the next few weeks.

**Closed by luisfarzati** 2015-07-18 01:59 UTC
Labels: in-development

**Comment by jgentes** [comment] 2015-07-19 23:26
Works great, thanks for the fix!

**Comment by nmstoker** [comment] 2016-04-05 16:34
Did this tidy-up get stuck? As far as I can see the problem is still happening with bower.

I solved it with a different (and decidedly temporary!) workaround but I'll try the suggestions above when I get a chance, although it would be good if this wasn't necessary :smiley:

**Comment by timelf123** [comment] 2016-05-13 16:55
Each provider that had a volunteer maintainer was split out of this repo. Some lingered here because no one stepped up to maintain.

If you wish to override the bower settings you can:

```
  "overrides": {
    "angulartics": {
      "main": [
        "src/angulartics.js"
      ],
      "dependencies": {
        "angular": ">= 1.1.5",
        "SHA-1": "*"
      }
    }
  }
```
