### ISSUE TITLE
Not working in firefox 25,MacOs

### ISSUE THREAD

**Issue by R11baka** [luisfarzati/angulartics#57] opened 2013-11-25 12:28 UTC
Failed when load module for google analytics in firefox 25,MacOs
angularJS 1.2
```
Error: [$injector:modulerr] Failed to instantiate module bdaycards due to:
[$injector:modulerr] Failed to instantiate module angulartics.google.analytics due to:
[$injector:nomod] Module 'angulartics.google.analytics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.0/$injector/nomod?p0=angulartics.google.analytics
minErr/<@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:78
setupModuleLoader/</module/<@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1500
ensure@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1434
module@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1496
createInjector/loadModules/<@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3520
forEach@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:300
loadModules@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3514
createInjector/loadModules/<@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3521
forEach@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:300
loadModules@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3514
createInjector@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3454
bootstrap/doBootstrap@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1282
bootstrap@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1297
angularInit@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1246
@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:20026
f.Callbacks/n@https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js:2
f.Callbacks/o.fireWith@https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js:2
.ready@https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js:2
B@https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js:2

http://errors.angularjs.org/1.2.0/$injector/modulerr?p0=angulartics.google.analytics&p1=%5B%24injector%3Anomod%5D%20Module%20'angulartics.google.analytics'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.0%2F%24injector%2Fnomod%3Fp0%3Dangulartics.google.analytics%0AminErr%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A78%0AsetupModuleLoader%2F%3C%2Fmodule%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1500%0Aensure%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1434%0Amodule%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1496%0AcreateInjector%2FloadModules%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3520%0AforEach%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A300%0AloadModules%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3514%0AcreateInjector%2FloadModules%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3521%0AforEach%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A300%0AloadModules%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3514%0AcreateInjector%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3454%0Abootstrap%2FdoBootstrap%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1282%0Abootstrap%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1297%0AangularInit%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1246%0A%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A20026%0Af.Callbacks%2Fn%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0Af.Callbacks%2Fo.fireWith%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0A.ready%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0AB%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0A
minErr/<@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:78
createInjector/loadModules/<@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3549
forEach@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:300
loadModules@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3514
createInjector/loadModules/<@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3521
forEach@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:300
loadModules@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3514
createInjector@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:3454
bootstrap/doBootstrap@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1282
bootstrap@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1297
angularInit@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:1246
@https://velton.appsorama.com:9007/facebook_apps/rybirthdays/web/1385382350/assets/angular/vendor/angular.js:20026
f.Callbacks/n@https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js:2
f.Callbacks/o.fireWith@https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js:2
.ready@https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js:2
B@https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js:2

http://errors.angularjs.org/1.2.0/$injector/modulerr?p0=bdaycards&p1=%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20angulartics.google.analytics%20due%20to%3A%0A%5B%24injector%3Anomod%5D%20Module%20'angulartics.google.analytics'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.0%2F%24injector%2Fnomod%3Fp0%3Dangulartics.google.analytics%0AminErr%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A78%0AsetupModuleLoader%2F%3C%2Fmodule%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1500%0Aensure%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1434%0Amodule%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1496%0AcreateInjector%2FloadModules%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3520%0AforEach%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A300%0AloadModules%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3514%0AcreateInjector%2FloadModules%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3521%0AforEach%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A300%0AloadModules%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3514%0AcreateInjector%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3454%0Abootstrap%2FdoBootstrap%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1282%0Abootstrap%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1297%0AangularInit%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1246%0A%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A20026%0Af.Callbacks%2Fn%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0Af.Callbacks%2Fo.fireWith%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0A.ready%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0AB%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0A%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.0%2F%24injector%2Fmodulerr%3Fp0%3Dangulartics.google.analytics%26p1%3D%255B%2524injector%253Anomod%255D%2520Module%2520'angulartics.google.analytics'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.2.0%252F%2524injector%252Fnomod%253Fp0%253Dangulartics.google.analytics%250AminErr%252F%253C%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A78%250AsetupModuleLoader%252F%253C%252Fmodule%252F%253C%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A1500%250Aensure%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A1434%250Amodule%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A1496%250AcreateInjector%252FloadModules%252F%253C%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A3520%250AforEach%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A300%250AloadModules%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A3514%250AcreateInjector%252FloadModules%252F%253C%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A3521%250AforEach%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A300%250AloadModules%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A3514%250AcreateInjector%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A3454%250Abootstrap%252FdoBootstrap%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A1282%250Abootstrap%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A1297%250AangularInit%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A1246%250A%2540https%253A%252F%252Fvelton.appsorama.com%253A9007%252Ffacebook_apps%252Frybirthdays%252Fweb%252F1385382350%252Fassets%252Fangular%252Fvendor%252Fangular.js%253A20026%250Af.Callbacks%252Fn%2540https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fjquery%252F1.7.1%252Fjquery.min.js%253A2%250Af.Callbacks%252Fo.fireWith%2540https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fjquery%252F1.7.1%252Fjquery.min.js%253A2%250A.ready%2540https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fjquery%252F1.7.1%252Fjquery.min.js%253A2%250AB%2540https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fjquery%252F1.7.1%252Fjquery.min.js%253A2%250A%0AminErr%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A78%0AcreateInjector%2FloadModules%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3549%0AforEach%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A300%0AloadModules%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3514%0AcreateInjector%2FloadModules%2F%3C%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3521%0AforEach%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A300%0AloadModules%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3514%0AcreateInjector%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A3454%0Abootstrap%2FdoBootstrap%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1282%0Abootstrap%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1297%0AangularInit%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A1246%0A%40https%3A%2F%2Fvelton.appsorama.com%3A9007%2Ffacebook_apps%2Frybirthdays%2Fweb%2F1385382350%2Fassets%2Fangular%2Fvendor%2Fangular.js%3A20026%0Af.Callbacks%2Fn%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0Af.Callbacks%2Fo.fireWith%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0A.ready%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0AB%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%3A2%0A
https://s-static.ak.facebook.com/connect/xd_arbiter.php?version=28
Line 13
```

but in Chrome  all working ok

**Comment by alarv** [comment] 2015-06-15 20:27
You have to inject the angulartics-ga file as well. On my bower installation I set:
```
angulartics/dist/angulartics-ga.min
```
and it worked

**Comment by timelf123** [comment] 2015-06-29 14:14
Closing for lack of updates. Feel free to reopen if you are still having problems with this, but I was not able to reproduce

**Closed by timelf123** 2015-06-29 14:14 UTC
Labels: bug, feedback-welcomed

**Comment by an-dev** [comment] 2015-08-18 15:28
The issue could be probably caused by third party plug-ins or extensions that are blocking angulartics from instantiating the _ga cookie or even hinder its loading in the page and eventually make a whole angular app.js crash.

I've reproduced the bug successfully by switching uBlock off in my developing environment, see pic related.

Browsers
    Firefox 38.0
    Chromium 37.0.2062.120



![screenshot from 2015-08-18 09 57 21](https://cloud.githubusercontent.com/assets/5052825/9334317/84dfd714-45ce-11e5-8b69-2634db5c94eb.png)
![screenshot from 2015-08-18 17 04 24](https://cloud.githubusercontent.com/assets/5052825/9334318/84e96202-45ce-11e5-8442-d80d9a8b6290.png)
![screenshot from 2015-08-18 17 27 58](https://cloud.githubusercontent.com/assets/5052825/9334320/84e98ec6-45ce-11e5-9f36-975546a6dc6f.png)

**Comment by NerdCowboy** [comment] 2021-01-29 16:01
This is the error I'm getting in Brave on Mac, so it being blocked is the issue for me. 

The entire website is inaccessible due to this error, so I would still consider this a bug—it should fail gracefully rather than take down the entire site.
